# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      CI: true

    steps:
    - name: display environment vars
      run: env

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.6.6, install our version of bundler and cache the gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
        bundler: 2.1.4
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run bundler-audit
      run: bundle exec bundle-audit update; bundle exec bundle-audit check

    - name: Run Tests
      run: bundle exec rake test

    - name: publish coverage reports
      uses: 5monkeys/cobertura-action@master
      with:
        path: ./coverage/coverage.xml
        minimum_coverage: 7
        repo_token: ${{ secrets.CI_COBERTURA_REPORTS_PUBLIC }}

    # - name: TODO - flog complexity report

    # - name: Post result to slack
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    #   if: always() # Pick up events even if the job fails or is canceled.
